package gui.side_dish;

import domain.SideDish;
import service.imp.SideDishServiceImp;
import session.Session;
import service.SideDishService;

/**
 *
 * @author Marko Milosevic
 */
public class DetailsSideDish extends javax.swing.JDialog {

    private final SideDish sideDish;
    private final SideDishService sideDishService;

    /**
     * Creates new form DetailsSideDish
     */
    public DetailsSideDish(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sideDish = (SideDish) Session.getInstance().getMap().get("selected.sideDish");
        sideDishService = new SideDishServiceImp();
        populateForm();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlFoodItem = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblMass = new javax.swing.JLabel();
        txtMass = new javax.swing.JTextField();
        lblEnergyValue = new javax.swing.JLabel();
        txtEnergyValue = new javax.swing.JTextField();
        pnlBasicNutrients = new javax.swing.JPanel();
        lblProtein = new javax.swing.JLabel();
        txtProtein = new javax.swing.JTextField();
        lblFats = new javax.swing.JLabel();
        txtFats = new javax.swing.JTextField();
        lblCarbohydrates = new javax.swing.JLabel();
        txtCarbohydrates = new javax.swing.JTextField();
        pnlProtectiveNutrients = new javax.swing.JPanel();
        pnlMinerals = new javax.swing.JPanel();
        lblCalcium = new javax.swing.JLabel();
        txtCalcium = new javax.swing.JTextField();
        lblIron = new javax.swing.JLabel();
        txtIron = new javax.swing.JTextField();
        pnlVitamins = new javax.swing.JPanel();
        lblVitaminA = new javax.swing.JLabel();
        txtVitaminA = new javax.swing.JTextField();
        lblVitaminB1 = new javax.swing.JLabel();
        txtVitaminB1 = new javax.swing.JTextField();
        lblVitaminB2 = new javax.swing.JLabel();
        txtVitaminB2 = new javax.swing.JTextField();
        lblNiacin = new javax.swing.JLabel();
        txtNiacin = new javax.swing.JTextField();
        lblVitaminC = new javax.swing.JLabel();
        txtVitaminC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalji izabrane namirnice");

        pnlFoodItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Vrsta namirnice, masa i energetska vrednost"));

        lblName.setText("Naziv");

        txtName.setEditable(false);

        lblMass.setText("Masa u gramima");

        txtMass.setEditable(false);

        lblEnergyValue.setText("Energetska vrednost kJ (Cal)");

        txtEnergyValue.setEditable(false);

        javax.swing.GroupLayout pnlFoodItemLayout = new javax.swing.GroupLayout(pnlFoodItem);
        pnlFoodItem.setLayout(pnlFoodItemLayout);
        pnlFoodItemLayout.setHorizontalGroup(
            pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMass)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFoodItemLayout.createSequentialGroup()
                        .addComponent(txtMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblEnergyValue)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnergyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFoodItemLayout.setVerticalGroup(
            pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFoodItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMass)
                    .addComponent(txtMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnergyValue)
                    .addComponent(txtEnergyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBasicNutrients.setBorder(javax.swing.BorderFactory.createTitledBorder("Osnovni hranljivi sastojci u gramima"));

        lblProtein.setText("Belancevine");

        txtProtein.setEditable(false);

        lblFats.setText("Masti");

        txtFats.setEditable(false);

        lblCarbohydrates.setText("Ugljeni hidrati");

        txtCarbohydrates.setEditable(false);

        javax.swing.GroupLayout pnlBasicNutrientsLayout = new javax.swing.GroupLayout(pnlBasicNutrients);
        pnlBasicNutrients.setLayout(pnlBasicNutrientsLayout);
        pnlBasicNutrientsLayout.setHorizontalGroup(
            pnlBasicNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicNutrientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProtein)
                .addGap(18, 18, 18)
                .addComponent(txtProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFats, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCarbohydrates, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCarbohydrates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBasicNutrientsLayout.setVerticalGroup(
            pnlBasicNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicNutrientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBasicNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProtein)
                    .addComponent(lblFats)
                    .addComponent(txtProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarbohydrates)
                    .addComponent(txtCarbohydrates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProtectiveNutrients.setBorder(javax.swing.BorderFactory.createTitledBorder("Zastitni hranljivi sastojci u miligramima"));

        pnlMinerals.setBorder(javax.swing.BorderFactory.createTitledBorder("Mineralni sastojci"));

        lblCalcium.setText("Kalcijum");

        txtCalcium.setEditable(false);

        lblIron.setText("Gvozdje");

        txtIron.setEditable(false);

        javax.swing.GroupLayout pnlMineralsLayout = new javax.swing.GroupLayout(pnlMinerals);
        pnlMinerals.setLayout(pnlMineralsLayout);
        pnlMineralsLayout.setHorizontalGroup(
            pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMineralsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCalcium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIron)
                    .addComponent(txtCalcium))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMineralsLayout.setVerticalGroup(
            pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMineralsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalcium)
                    .addComponent(txtCalcium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMineralsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIron)
                    .addComponent(txtIron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVitamins.setBorder(javax.swing.BorderFactory.createTitledBorder("Vitamini"));

        lblVitaminA.setText("Vitamin A");

        txtVitaminA.setEditable(false);

        lblVitaminB1.setText("Vitamin B1");

        txtVitaminB1.setEditable(false);

        lblVitaminB2.setText("Vitamin B2");

        txtVitaminB2.setEditable(false);

        lblNiacin.setText("Niacin");

        txtNiacin.setEditable(false);

        lblVitaminC.setText("Vitamin C");

        txtVitaminC.setEditable(false);

        javax.swing.GroupLayout pnlVitaminsLayout = new javax.swing.GroupLayout(pnlVitamins);
        pnlVitamins.setLayout(pnlVitaminsLayout);
        pnlVitaminsLayout.setHorizontalGroup(
            pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVitaminsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVitaminA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVitaminB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVitaminB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVitaminB1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVitaminB2)
                    .addComponent(txtVitaminA))
                .addGap(18, 18, 18)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNiacin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVitaminC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNiacin)
                    .addComponent(txtVitaminC))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        pnlVitaminsLayout.setVerticalGroup(
            pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVitaminsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblVitaminB1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVitaminsLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVitaminA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVitaminA)
                    .addComponent(lblNiacin)
                    .addComponent(txtNiacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVitaminB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVitaminC)
                    .addComponent(txtVitaminC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVitaminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVitaminB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVitaminB2))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProtectiveNutrientsLayout = new javax.swing.GroupLayout(pnlProtectiveNutrients);
        pnlProtectiveNutrients.setLayout(pnlProtectiveNutrientsLayout);
        pnlProtectiveNutrientsLayout.setHorizontalGroup(
            pnlProtectiveNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProtectiveNutrientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMinerals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlVitamins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProtectiveNutrientsLayout.setVerticalGroup(
            pnlProtectiveNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProtectiveNutrientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProtectiveNutrientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMinerals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVitamins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlProtectiveNutrients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFoodItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBasicNutrients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFoodItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBasicNutrients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProtectiveNutrients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCalcium;
    private javax.swing.JLabel lblCarbohydrates;
    private javax.swing.JLabel lblEnergyValue;
    private javax.swing.JLabel lblFats;
    private javax.swing.JLabel lblIron;
    private javax.swing.JLabel lblMass;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNiacin;
    private javax.swing.JLabel lblProtein;
    private javax.swing.JLabel lblVitaminA;
    private javax.swing.JLabel lblVitaminB1;
    private javax.swing.JLabel lblVitaminB2;
    private javax.swing.JLabel lblVitaminC;
    private javax.swing.JPanel pnlBasicNutrients;
    private javax.swing.JPanel pnlFoodItem;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMinerals;
    private javax.swing.JPanel pnlProtectiveNutrients;
    private javax.swing.JPanel pnlVitamins;
    private javax.swing.JTextField txtCalcium;
    private javax.swing.JTextField txtCarbohydrates;
    private javax.swing.JTextField txtEnergyValue;
    private javax.swing.JTextField txtFats;
    private javax.swing.JTextField txtIron;
    private javax.swing.JTextField txtMass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNiacin;
    private javax.swing.JTextField txtProtein;
    private javax.swing.JTextField txtVitaminA;
    private javax.swing.JTextField txtVitaminB1;
    private javax.swing.JTextField txtVitaminB2;
    private javax.swing.JTextField txtVitaminC;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        String name = sideDish.getName();
        sideDishService.checkValue(txtName, name);

        String mass = sideDish.getMass();
        sideDishService.checkValue(txtMass, mass);

        String energyValue = sideDish.getEnergyValue();
        sideDishService.checkValue(txtEnergyValue, energyValue);

        String protein = String.valueOf(sideDish.getProtein());
        sideDishService.checkValue(txtProtein, protein);

        String fats = String.valueOf(sideDish.getFats());
        sideDishService.checkValue(txtFats, fats);

        String carbohydrates = String.valueOf(sideDish.getCarbohydrates());
        sideDishService.checkValue(txtCarbohydrates, carbohydrates);

        String calcium = String.valueOf(sideDish.getCalcium());
        sideDishService.checkValue(txtCalcium, calcium);

        String iron = String.valueOf(sideDish.getIron());
        sideDishService.checkValue(txtIron, iron);

        String vitaminA = String.valueOf(sideDish.getVitaminA());
        sideDishService.checkValue(txtVitaminA, vitaminA);

        String vitaminB1 = String.valueOf(sideDish.getVitaminB1());
        sideDishService.checkValue(txtVitaminB1, vitaminB1);

        String vitaminB2 = String.valueOf(sideDish.getVitaminB2());
        sideDishService.checkValue(txtVitaminB2, vitaminB2);

        String niacin = String.valueOf(sideDish.getNiacin());
        sideDishService.checkValue(txtNiacin, niacin);

        String vitaminC = String.valueOf(sideDish.getVitaminC());
        sideDishService.checkValue(txtVitaminC, vitaminC);
    }
}
