package gui.advice;

import service.imp.TechnicalTermServiceImp;
import service.TechnicalTermService;

/**
 *
 * @author Marko Milosevic
 */
public class TechnicalTermForm extends javax.swing.JDialog {

    private final TechnicalTermService technicalTermService;

    /**
     * Creates new form TechnicalTermForm
     */
    public TechnicalTermForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        technicalTermService = new TechnicalTermServiceImp();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTechnicalTerm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        btnTechnicalTerm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Strucni izrazi");

        comboTechnicalTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Termicka obrada", "Kuvanje", "Parenje ili proces vlazne toplote", "Dinstanje", "Przenje", "Pecenje", "Blansiranje", "Pohovanje", "Kombinovani procesi", "Zaprzavanje", "Zamascivanje", "Zacinjavanje", "Glaziranje", "Gratiniranje", "Sotiranje", "Dekantiranje", "Paniranje", "Pasiranje", "Fond" }));
        comboTechnicalTerm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboTechnicalTerm.setDoubleBuffered(true);

        txtText.setEditable(false);
        txtText.setColumns(20);
        txtText.setRows(5);
        jScrollPane1.setViewportView(txtText);

        btnTechnicalTerm.setText("Prikazi definiciju izabranog strucnog izraza");
        btnTechnicalTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechnicalTermActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboTechnicalTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTechnicalTerm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTechnicalTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTechnicalTerm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTechnicalTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechnicalTermActionPerformed
        String word = String.valueOf(comboTechnicalTerm.getSelectedItem());
        technicalTermService.write(word, txtText);
    }//GEN-LAST:event_btnTechnicalTermActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTechnicalTerm;
    private javax.swing.JComboBox<String> comboTechnicalTerm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
