package gui.advice;

import domain.ThermalProcessing;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import service.imp.ThermalProcessingServiceImp;
import table.TableThermalProcessing;
import service.ThermalProcessingService;

/**
 *
 * @author Marko Milosevic
 */
public class ThermalProcessingForm extends javax.swing.JDialog {

    private final ThermalProcessingService thermalProcessingService;

    /**
     * Creates new form ThermalProcessingForm
     */
    public ThermalProcessingForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        thermalProcessingService = new ThermalProcessingServiceImp();
        populateTable();
        setTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFoodItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Termicka obrada pojedinih jela");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblFoodItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFoodItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        populateTable();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFoodItem;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try {
            List<ThermalProcessing> thermalProcessings = thermalProcessingService.getAll();
            TableModel tm = new TableThermalProcessing(thermalProcessings);
            tblFoodItem.setModel(tm);
            setTable();
        } catch (Exception ex) {
        }
    }

    private void setTable() {
        tblFoodItem.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblFoodItem.getColumnModel().getColumn(0).setPreferredWidth(21);
        tblFoodItem.getColumnModel().getColumn(1).setPreferredWidth(300);
        tblFoodItem.getColumnModel().getColumn(2).setPreferredWidth(280);
        tblFoodItem.getColumnModel().getColumn(3).setPreferredWidth(280);
    }
}
