package gui.recipe;

import domain.Recipe;
import gui.recipe.normative.NormativeForm;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import service.RecipeService;
import service.imp.RecipeServiceImp;
import session.Session;
import table.TableRecipe;

/**
 *
 * @author Marko Milosevic
 */
public class ReadyMadeIndustrialMealForm extends javax.swing.JDialog {

    private final RecipeService recipeService;

    /**
     * Creates new form ReadyMadeIndustrialMealForm
     */
    public ReadyMadeIndustrialMealForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        recipeService = new RecipeServiceImp();
        populateTable();
        setTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecipe = new javax.swing.JTable();
        btnDetalils = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gotova industrijska jela (sterilisana)");

        tblRecipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecipe);

        btnDetalils.setText("Detalji");
        btnDetalils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalilsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalils))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalils)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalilsActionPerformed
        int selectedRow = tblRecipe.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali recepturu!");
        } else {
            TableModel tm = tblRecipe.getModel();
            TableRecipe tr = (TableRecipe) tm;
            Recipe recipe = tr.getRecipe(selectedRow);

            Session.getInstance().getMap().put("selected.recipe", recipe);

            new NormativeForm(null, true).setVisible(true);
        }
    }//GEN-LAST:event_btnDetalilsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalils;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecipe;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try {
            List<Recipe> recipes = recipeService.getReadyMeals();
            TableModel tm = new TableRecipe(recipes);
            tblRecipe.setModel(tm);
            setTable();
        } catch (Exception ex) {
        }
    }

    private void setTable() {
        tblRecipe.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblRecipe.getColumnModel().getColumn(0).setPreferredWidth(85);
        tblRecipe.getColumnModel().getColumn(1).setPreferredWidth(272);
    }
}
